version: '3'

services:

  quotes:
    image: odarbelaeze/quotes:broken
    environment:
      - QUOTES_PREFIX=/api
    networks:
      - proxy
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.servicePath=/api
        - com.df.port=8000

  ui:
    image: odarbelaeze/quotes-ui:32fae1374501c342ceabca5ffb6ff116c7fdf47f
    networks:
      - proxy
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.servicePath=/
        - com.df.servicePathExclude=/api
        - com.df.port=80

networks:
  proxy:
    external: true

